### ISSUE TITLE
closure-make-deps doesn't return a non-zero exit code on failure

### ISSUE THREAD

**Issue by joeyparrish** [google/closure-library#1162]
I recently made a mistake in [shaka-project/shaka-player](https://github.com/shaka-project/shaka-player) in which I left out a critical file while generating deps for the project (`dist/locales.js`, in particular).  `closure-make-deps` complained, and didn't generate any output, but still used exit code 0.  This caused our project's build system to continue as if everything were okay.

```sh
$ ./node_modules/.bin/closure-make-deps -r demo lib ui third_party --closure-path node_modules/google-closure-library/closure/goog
SourceError: Error in source file "/path/to/shaka-player/ui/ad_counter.js": Could not find "shaka.ui.Locales".
    at validate (/path/to/shaka-player/node_modules/google-closure-deps/lib/depgraph.js:363:19)
    at Graph.validate (/path/to/shaka-player/node_modules/google-closure-deps/lib/depgraph.js:415:9)
    at main (/path/to/shaka-player/node_modules/google-closure-deps/bin/closuremakedeps.js:296:30)
    at async /path/to/shaka-player/node_modules/google-closure-deps/bin/closuremakedeps.js:312:22
$ echo $?
0
```

This tool should return non-zero when it fails.

I don't think our project specifics are important in this issue, but please let me know if any additional details are required.  Thanks!

**Comment by shicks** [comment]
Wow, that's definitely wrong.  I'll put together a patch to make it return non-zero on failure.  If there are only warnings, it still emits a deps file, and so I'll have it continue to return zero in that case.
