### ISSUE TITLE
closurebuilder.py not working on Windows

### ISSUE THREAD

**Issue by prahladyeri** [google/closure-library#482]
I'm going through this [Using ClosureBuilder Tutorial](https://developers.google.com/closure/library/docs/closurebuilder). As mentioned in the tutorial, I gave the following command to calculate dependencies:

    python closure-library/closure/bin/build/closurebuilder.py \ --root=closure-library/ \ --root=myproject/ \ --namespace="myproject.start"

However, I'm gettng this error:

	closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
	Traceback (most recent call last):
	  File "closure-library/closure/bin/build/closurebuilder.py", line 287, in <module>
		main()
	  File "closure-library/closure/bin/build/closurebuilder.py", line 216, in main
		sources.add(_PathSource(js_path))
	  File "closure-library/closure/bin/build/closurebuilder.py", line 175, in __init__
		super(_PathSource, self).__init__(source.GetFileContents(path))
	  File "D:\html\closuredemo\closure-library\closure\bin\build\source.py", line 123, in GetFileContents
		fileobj = open(path)
	IOError: [Errno 2] No such file or directory: '\\'

Please advice.

**Comment by prahladyeri** [comment]
Sorry, realized that those backslashes were only required for multi-line python commands! So stripping them, the command runs without any issues now:

    python closure-library/closure/bin/build/closurebuilder.py --root=closure-library/ --root=myproject/ --namespace="myproject.start"
