### ISSUE TITLE
_ParseJavaVersion fails to parse 'openjdk version "9-Ubuntu"'

### ISSUE THREAD

**Issue by attila-horvath** [google/closure-library#794]
```
/home/attila/closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
/home/attila/closure-library/closure/bin/build/closurebuilder.py: 1574 sources scanned.
/home/attila/closure-library/closure/bin/build/closurebuilder.py: Building dependency tree..
/home/attila/closure-library/closure/bin/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
is prefererred over using this script for performing JavaScript compilation.

Please migrate your codebase.

See:
https://github.com/google/closure-compiler/wiki/Managing-Dependencies

Traceback (most recent call last):
  File "/home/attila/closure-library/closure/bin/build/closurebuilder.py", line 293, in <module>
    main()
  File "/home/attila/closure-library/closure/bin/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/home/attila/closure-library/closure/bin/build/jscompiler.py", line 147, in Compile
    args = _GetJsCompilerArgs(compiler_jar_path, java_version, jvm_flags)
  File "/home/attila/closure-library/closure/bin/build/jscompiler.py", line 74, in _GetJsCompilerArgs
    if java_version < (1, 7):
TypeError: unorderable types: NoneType() < tuple()
```

https://github.com/google/closure-library/blob/master/closure/bin/build/jscompiler.py#L145
ParseJavaVersion returns None.

```
java -version
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b134-2ubuntu1)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b134-2ubuntu1, mixed mode)
```

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
