### ISSUE TITLE
[Python3 ] closurebuilder.py: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Morabaraba** [google/closure-library#849]
Hi

I got a error using `closurebuilder.py` with python 3.5 and 3.6:

```sh
Traceback (most recent call last):
  File "closure-library/closure/bin/build/closurebuilder.py", line 293, in <module>
    main()
  File "closure-library/closure/bin/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/static/closure/closure-library/closure/bin/build/jscompiler.py", line 151, in Compile
    flags_file = _GetFlagFile(source_paths, compiler_flags)
  File "/static/closure/closure-library/closure/bin/build/jscompiler.py", line 122, in _GetFlagFile
    flags_file.write(' '.join(args))
  File "/venv/lib/python3.6/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

If I change the first line in `closurebuilder.py` to `#!/usr/bin/env python2` all work as expected.

I did see the migrate warning, so I don't think anybody want to spend time on this?

Maybe make the `closurebuilder.py` tool a python2 tool only and hardcode it to `python2`?

**Comment by shicks** [comment]
Please feel free to send a PR that does this.
