### ISSUE TITLE
Unable to get property 'clientX' of undefined or null reference

### ISSUE THREAD

**Issue by supersteves** [google/closure-library#927]
Seen several times in the field on IE11:

```
ErrorObj: stack: TypeError: Unable to get property 'clientX' of undefined or null reference 
at null (/_global_/devbuilder/codebase/Mobile/ClosureLibrary/closure-library/goog/events/browserevent.js:260:4) 
at null (/_global_/devbuilder/codebase/Mobile/ClosureLibrary/closure-library/goog/events/browserevent.js:189:4) 
at null (/_global_/devbuilder/codebase/Mobile/ClosureLibrary/closure-library/goog/events/events.js:856:2) 
at null (/_global_/devbuilder/codebase/Mobile/ClosureLibrary/closure-library/goog/debug/errorhandler.js:183:6) 
at null (/_global_/devbuilder/codebase/Mobile/ClosureLibrary/closure-library/goog/events/events.js:278:8)
```

This happens at [browserevent.js:308](https://github.com/google/closure-library/blob/master/closure/goog/events/browserevent.js#L308) presumably because `relevantTouch` is undefined and not caught by `goog.isNull` in the line above. I'm guessing this is because of [browserevent.js:280](https://github.com/google/closure-library/blob/master/closure/goog/events/browserevent.js#L280):
``` javascript
var relevantTouch = e.changedTouches ? e.changedTouches[0] : null;
```
and presumably `e.changedTouches` is zero length in certain (unknown) circumstances.

### Suggested fix
At line 280:
``` javascript
var relevantTouch = e.changedTouches && e.changedTouches.length ? e.changedTouches[0] : null;
```
Plus for extra security at 307:
``` javascript
if (goog.isDefAndNotNull(relevantTouch)) {
```

**Comment by supersteves** [comment]
Thanks! Sorry I didn't get around to this myself.
